import os
from dotenv import load_dotenv

load_dotenv()

# HubSpot
HUBSPOT_API_KEY = os.getenv("HUBSPOT_API_KEY")

# Google Cloud
GOOGLE_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_CREDENTIALS

BIGQUERY_PROJECT_ID = os.getenv("BIGQUERY_PROJECT_ID")
DATASET_ID = os.getenv("BIGQUERY_DATASET_ID")

# BigQuery Table Names
BQ_COMPANY_TABLE = os.getenv("BIGQUERY_COMPANY_TABLE")
BQ_OWNER_TABLE = os.getenv("BIGQUERY_OWNER_TABLE")
BQ_DEALS_TABLE = os.getenv("BIGQUERY_DEALS_TABLE")
BQ_STAGE_MAPPING_TABLE = os.getenv("BIGQUERY_STAGE_MAPPING_TABLE")
BQ_PIPELINE_UNITS_TABLE = os.getenv("BIGQUERY_PIPELINE_UNITS_TABLE")
BQ_SNAPSHOT_REGISTRY_TABLE = os.getenv("BIGQUERY_SNAPSHOT_REGISTRY_TABLE")
BQ_PIPELINE_SCORE_HISTORY_TABLE = os.getenv("BIGQUERY_PIPELINE_SCORE_HISTORY_TABLE")


print(f"📦 Loaded owner table from .env: {BQ_OWNER_TABLE}")
